require("plugins/autopairs")
require("plugins/comment")
require("plugins/nvimtree")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/bufferline")
require("plugins/lualine")
